[package]
name = "network-administrator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
http-body-util = "0.1.3"
hyper = { version = "1.8.1", features = ["full"] }
hyper-util = { version = "0.1.18", features = ["full"] }
rustls = "0.23.35"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
uuid = { version = "1.18.1", features = ["v4"] }
